source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
inhibit_all_warnings!
use_modular_headers!
use_frameworks! :linkage => :static

install! 'cocoapods',
:generate_multiple_pod_projects => true

plugin 'cocoapods-xcremotecache'

xcremotecache({
    'cache_addresses' => ['http://localhost:8080/cache/movieapp'],
    'primary_repo' => 'git@github.com-dwirandyh:dwirandyh/xcremotecache-modular-example.git',
    'primary_branch' => 'main',
    'mode' => 'consumer', # consumer / producer
    'final_target' => 'MovieApp', # producer only
    'xcrc_location' => '../tools/xcremotecache',
    'exclude_targets' => ['React-Core'],
    'thinning_enabled' => true,
    'custom_rewrite_envs' => ['PODS_TARGET_SRCROOT']
})


target 'MovieApp' do

  pod 'User', :path => './Modules/User/'
  pod 'Analytic', :path => './Modules/Analytic/'

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'SDWebImage', '5.0'

  target 'MovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieAppUITests' do
    # Pods for testing
  end

end
