platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks! :linkage => :static

target 'MovieApp' do

  pod 'User', :path => './Modules/User/'

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'SDWebImage', '5.0'

  target 'MovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieAppUITests' do
    # Pods for testing
  end

end
