source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
inhibit_all_warnings!
use_modular_headers!
use_frameworks! :linkage => :static

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true

plugin 'cocoapods-xcremotecache'

xcremotecache({
    'cache_addresses' => ['http://localhost:8080/cache/movieapp'],
    'primary_repo' => 'git@github.com-dwirandyh:dwirandyh/xcremotecache-modular-example.git',
    'primary_branch' => 'main',
    'mode' => 'producer',
    'final_target' => 'Debug',
    'xcrc_location' => '../tools/xcremotecache',
})


target 'MovieApp' do

  pod 'User', :path => './Modules/User/'

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'SDWebImage', '5.0'

  target 'MovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieAppUITests' do
    # Pods for testing
  end

end
