source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
inhibit_all_warnings!
use_modular_headers!
use_frameworks! :linkage => :static

install! 'cocoapods',
:generate_multiple_pod_projects => true

target 'Launcher' do

  # Pods for Launcher
  pod 'Analytic', :path => './'	
end
